import {randomUUID} from 'node:crypto';
export const POLICY_VERSION='2026-10-07-free';
export const DAY=86400000;
export function billingConfig(){const operator=process.env.OPERATOR_NAME||'',email=process.env.SUPPORT_EMAIL||'',address=process.env.BUSINESS_ADDRESS||'',upi=process.env.UPI_ID||'',payee=process.env.UPI_PAYEE_NAME||'';return {operator,email,address,upi,payee,enabled:false,amount:100,days:30,policyVersion:POLICY_VERSION}}
export function registerBilling(app,{pool,auth,admin,asyncRoute}){
app.get('/api/billing/config',(req,res)=>res.json(billingConfig()));
app.post('/api/listings/:id/renewals',auth,asyncRoute(async(req,res)=>{const config=billingConfig();if(!config.enabled)return res.status(503).json({error:'Payment collection is not enabled. Do not send money.'});if(req.body.policyVersion!==POLICY_VERSION||req.body.accepted!==true)return res.status(400).json({error:'Accept the current renewal terms'});const ref=String(req.body.reference||'').trim();if(!/^\d{12}$/.test(ref))return res.status(400).json({error:'Enter the 12-digit UPI transaction reference'});const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM listings WHERE id=$1 AND owner=$2 FOR UPDATE',[req.params.id,req.user.id]);const l=rows[0];if(!l||l.status!=='approved'||!l.first_published)return res.status(400).json({error:'Only approved listings can be renewed'});const pending=await client.query("SELECT id FROM renewals WHERE listing=$1 AND status='pending'",[l.id]);if(pending.rowCount)return res.status(409).json({error:'Your payment is already awaiting verification'});await client.query('INSERT INTO renewals(id,listing,owner,reference,amount,policy_version) VALUES($1,$2,$3,$4,100,$5)',[randomUUID(),l.id,req.user.id,ref,POLICY_VERSION]);await client.query('COMMIT');res.status(201).json({ok:true})}catch(e){if(e.code==='23505')return res.status(409).json({error:'This payment reference has already been submitted'});throw e}finally{await client.query('ROLLBACK');client.release()}}));
app.get('/api/renewals',auth,asyncRoute(async(req,res)=>{res.json((await pool.query('SELECT * FROM renewals WHERE owner=$1 ORDER BY created DESC',[req.user.id])).rows)}));
app.get('/api/admin/renewals',auth,admin,asyncRoute(async(req,res)=>{res.json((await pool.query("SELECT r.*,l.data->>'title' AS title,l.data->>'name' AS owner_name FROM renewals r JOIN listings l ON l.id=r.listing ORDER BY r.created DESC LIMIT 200")).rows)}));
app.post('/api/admin/renewals/:id',auth,admin,asyncRoute(async(req,res)=>{const {status}=req.body;if(!['verified','rejected'].includes(status))return res.status(400).json({error:'Invalid payment decision'});const note=String(req.body.note||'').trim().slice(0,500);if(status==='rejected'&&!note)return res.status(400).json({error:'Give the owner a rejection reason'});const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM renewals WHERE id=$1 FOR UPDATE',[req.params.id]);const r=rows[0];if(!r)return res.status(404).json({error:'Payment request not found'});if(r.status!=='pending')return res.status(409).json({error:'This request has already been decided'});if(status==='verified'){const listing=await client.query('SELECT * FROM listings WHERE id=$1 FOR UPDATE',[r.listing]);if(listing.rows[0]?.status!=='approved')return res.status(409).json({error:'Listing is not approved. Resolve its status or refund payment before verification.'});await client.query("UPDATE listings SET expires_at=GREATEST(expires_at,NOW())+INTERVAL '30 days' WHERE id=$1",[r.listing])}await client.query('UPDATE renewals SET status=$1,note=$2,reviewer=$3,reviewed=NOW() WHERE id=$4',[status,note,req.user.id,r.id]);await client.query('COMMIT');res.json({ok:true})}finally{await client.query('ROLLBACK');client.release()}}));
}
