import useBackNavigation from './useBackNavigation.js';
import Chat from './Chat.jsx';
import {PolicyLinks} from './Billing.jsx';
import React,{useState,useEffect} from 'react';
import {House,Plus,Search,MapPin,Heart,MessageCircle,ArrowRight,X,Send,ShieldCheck,UserRound,LogIn,LogOut,LayoutGrid,Trees,LandPlot,Building2,SlidersHorizontal,Flag,Pencil,Trash2,CheckCircle,ArrowLeft,BedDouble,Wallet,IndianRupee,KeyRound,Download,Share2,Copy} from 'lucide-react';

export async function api(url,opts={}){const res=await fetch('/api'+url,{...opts,headers:opts.body instanceof FormData?{}:{'Content-Type':'application/json'},credentials:'same-origin'});const d=await res.json();if(!res.ok)throw Error(d.error||'Request failed');return d}
const rentalAreas=['Gokuldham', 'Ayodhya Gate', 'Zanda chowk', 'Jalaram chowk', 'Old kosamba', 'Tiranga chowk', 'Dadari Road'];
const formatOwnerName=value=>value.trim().replace(/\s+/g,' ').toLocaleLowerCase('en-IN').replace(/(^|[\s\-’'])\p{L}/gu,part=>part.toLocaleUpperCase('en-IN'));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const listingPhotos=p=>Array.isArray(p.photos)&&p.photos.length?p.photos:(p.image?[p.image]:[]);
function PhotoSlider({property,detail=false}){const photos=listingPhotos(property);if(!photos.length)return <div className={'no-property-photo '+(detail?'detail-image':'')}><House size={48}/><span>No photo added</span></div>;return <div className={'photo-slider '+(detail?'detail-slider':'')} aria-label={`${property.title} photos`}>{photos.map((src,index)=><img key={`${src}-${index}`} src={src} alt={index?`${property.title} photo ${index+1}`:property.title}/>)}
{photos.length>1&&<><span className="photo-count">{photos.length} photos</span><div className="photo-dots" aria-hidden="true">{photos.map((_,index)=><span key={index}/>)}</div></>}</div>}
export default function Live(){const[user,U]=useState(null),[ready,R]=useState(false),[tab,T]=useState('explore'),[rows,L]=useState([]),[mine,M]=useState([]),[pending,P]=useState([]),[reports,RP]=useState([]),[convs,C]=useState([]),[chat,CH]=useState(null),[modal,MO]=useState(null),[detail,D]=useState(null),[query,Q]=useState(''),[type,TY]=useState(''),[budget,BU]=useState(''),[notice,N]=useState(''),[shareOptions,SO]=useState(false),[shareTarget,ST]=useState(()=>new URLSearchParams(window.location.search).get('listing')),[saved,S]=useState(()=>{try{return JSON.parse(localStorage.getItem('lv-live-saved')||'[]')}catch{return []}});
const goBack=useBackNavigation({tab,chat,modal,detail,shareOptions},next=>{T(next.tab);CH(next.chat);MO(next.modal);D(next.detail);SO(next.shareOptions)});
const[installPrompt,IP]=useState(null);useEffect(()=>{const handler=e=>{e.preventDefault();IP(e)};const done=()=>IP(null);window.addEventListener('beforeinstallprompt',handler);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('beforeinstallprompt',handler);window.removeEventListener('appinstalled',done)}},[]);async function install(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;IP(null)}else N('To install: Android Chrome menu → Install app / Add to Home screen. On iPhone: Safari → Share → Add to Home Screen.')}const gu=false;const t=(english)=>english;function error(e){N(e.message||e)}
async function refresh(){try{const listings=await api('/listings');L(listings);if(shareTarget){const target=listings.find(p=>p.id===shareTarget);if(target)D(target);else N('This shared home is no longer available. Browse the current rentals below.');ST(null);}if(user){S(await api('/favourites'));M(await api('/mine'));if(user.admin){P(await api('/admin/listings'));RP(await api('/admin/reports'))}}}catch(e){error(e)}}
useEffect(()=>{api('/me').then(d=>U(d.user)).catch(error).finally(()=>R(true))},[]);
useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[user,shareTarget]);
useEffect(()=>{if(!user)return;let alive=true,busy=false;async function load(){if(busy||document.hidden)return;busy=true;try{const rows=await api('/conversations');if(alive)C(rows)}catch(e){if(alive)error(e)}finally{busy=false}}load();const timer=setInterval(load,2000);document.addEventListener('visibilitychange',load);return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',load)}},[user]);
const unreadCount=convs.reduce((total,c)=>total+(c.unread||0),0);
function needLogin(){if(!user){window.location.href='/auth/google';return false}return true}
async function action(fn){try{await fn();await refresh()}catch(e){error(e)}}
async function save(id){if(user){await action(()=>api('/favourites/'+id,{method:saved.includes(id)?'DELETE':'POST'}));return}const s=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];S(s);localStorage.setItem('lv-live-saved',JSON.stringify(s))}
async function startChat(p){if(!needLogin())return;await action(async()=>{const c=await api('/conversations',{method:'POST',body:JSON.stringify({listing:p.id})});CH({id:c.id,data:p});T('messages');D(null)})}
function shareData(){return {title:'KosRent — Homes for rent in Kosamba',text:'Find a home or rent out your home in Kosamba with KosRent.',url:new URL('/',window.location.origin).toString()}}
async function shareApp(){const data=shareData();if(navigator.share){try{await navigator.share(data);return}catch(e){if(e.name==='AbortError')return}}SO(true)}
async function copyShare(){try{await navigator.clipboard.writeText(shareData().url);N('KosRent app link copied.');goBack()}catch{N('Copy the app link displayed below.')}}
async function report(p){if(!needLogin())return;const reason=window.prompt(t('Why are you reporting this?','રિપોર્ટ કરવાનું કારણ લખો'));if(reason)await action(async()=>{await api('/reports',{method:'POST',body:JSON.stringify({listing:p.id,reason})});N(t('Report sent for review.','રિપોર્ટ સમીક્ષા માટે મોકલાયો.'))})}
const visible=(tab==='mine'?mine:tab==='admin'?pending:rows).filter(p=>(tab!=='saved'||saved.includes(p.id))&&p.purpose==='rent'&&(tab==='mine'||!type||p.configuration===type)&&String(p.village).trim().toLowerCase()==='kosamba'&&(tab==='mine'||!budget||p.price<=Number(budget))&&(tab==='mine'||`${p.title} ${p.locality||''} ${p.address||''} ${p.village} ${p.district}`.toLowerCase().includes(query.toLowerCase())));
return <><header className="app-header"><a className="brand" href="/" onClick={e=>{e.preventDefault();CH(null);MO(null);D(null);T('explore')}}><span className="brand-icon"><House/></span>KosRent<span className="brand-dot">.</span></a><div className="town-label">Only for Kosamba<small>Find your place.</small></div><div className="header-actions"><button className="app-icon" aria-label="Share KosRent app" onClick={shareApp}><Share2 size={20}/></button><button className="app-icon" aria-label="Install KosRent" onClick={install}><Download size={20}/></button>{user?.admin&&<button className="app-icon" aria-label={t('Moderation','સમીક્ષા')} onClick={()=>T('admin')}><ShieldCheck size={22}/></button>}<button className="app-icon" aria-label={t('Profile','પ્રોફાઇલ')} onClick={()=>MO('profile')}><UserRound size={23}/></button></div></header>
<nav className="bottom-nav" aria-label={t('Main navigation','મુખ્ય નેવિગેશન')}>{[['explore',House,'Home','હોમ'],['saved',Heart,'Saved','સાચવેલી'],['messages',MessageCircle,'Chats','ચેટ'],['profile',UserRound,'Profile','પ્રોફાઇલ']].map(([key,Icon,en,gj])=><button key={key} className={(tab===key?'active ':'')+(key==='add'?'nav-add':'')} aria-label={t(en,gj)} aria-current={tab===key?'page':undefined} onClick={()=>{if(key==='profile'){MO('profile');return}if(key==='add'){if(needLogin())MO({});return}if(key==='messages'&&!needLogin())return;CH(null);T(key);window.scrollTo({top:0,behavior:'smooth'})}}><span><Icon size={23}/>{key==='messages'&&unreadCount>0&&<span className="nav-unread" aria-label={`${unreadCount} unread messages`}>{unreadCount}</span>}</span><small>{t(en,gj)}</small></button>)}</nav>
{shareOptions&&<div className="overlay"><section className="modal profile-sheet" role="dialog" aria-modal="true" aria-label="Share KosRent"><button className="close" aria-label="Close sharing options" onClick={goBack}><X/></button><div className="modal-content"><h2>Share KosRent</h2><p>Invite others to find or rent out a home in Kosamba.</p><div className="share-options"><a className="primary" target="_blank" rel="noopener noreferrer" href={'https://wa.me/?text='+encodeURIComponent(shareData().text+' '+shareData().url)}>Share on WhatsApp</a><button onClick={copyShare}><Copy size={16}/> Copy app link</button><input aria-label="KosRent app link" readOnly value={shareData().url} onFocus={e=>e.target.select()}/></div></div></section></div>}
{notice&&<div className="live-notice" role="status">{notice}<button onClick={()=>N('')} aria-label="Dismiss"><X size={16}/></button></div>}
{tab!=='messages'?<><main id="properties"><div className="rental-modes"><button className={tab==='explore'?'selected':''} onClick={()=>T('explore')}><Search size={24}/>{t('Find a home','ઘર શોધો')}</button><button onClick={()=>{if(needLogin())MO({})}}><KeyRound size={24}/>{t('Rent out a home','મારું ઘર ભાડે આપો')}</button></div><div className="section-top"><div><div className="eyebrow muted">{t('A PLACE FOR EVERY POSSIBILITY','દરેક શક્યતા માટે એક જગ્યા')}</div><h2>{tab==='mine'?t('Your listings','તમારી મિલકતો'):tab==='admin'?t('Moderation','લિસ્ટિંગની સમીક્ષા'):tab==='saved'?'Saved flats':t('Available flats','ભાડે ઉપલબ્ધ')}</h2><p>{t('Listings are owner-provided. Verify details before renting.','લિસ્ટિંગ સમીક્ષા કાયદેસર માલિકી ચકાસતી નથી.')}</p></div></div><div className="toolbar"><div className="bhk-filters" role="group" aria-label="Filter flats by bedrooms">{['','1 BHK','2 BHK','3 BHK'].map(value=><button key={value} className={type===value?'selected':''} aria-pressed={type===value} onClick={()=>TY(value)}>{value&&<BedDouble size={15}/>} {value||'All'}</button>)}</div><span>{visible.length} {t('properties','મિલકતો')}</span><label className="text-search"><Search size={16}/><input value={query} onChange={e=>Q(e.target.value)} placeholder={t('Search places…','સ્થળ શોધો…')} aria-label="Search properties"/></label></div><div className="grid" style={{marginTop:25}}>{visible.map(p=><article className="property" key={p.id}><div className="property-image" onClick={()=>D(p)}><PhotoSlider property={p}/><span className="tag">{p.status==='approved'?(p.expired?'Expired':tab==='mine'?'Published':'Available'):p.status==='pending'?'Awaiting review':p.status==='rejected'?'Not approved':p.status==='removed'?'Removed':p.status==='rented'?'Rented':p.status}</span><button className={'heart '+(saved.includes(p.id)?'is-saved':'')} aria-label="Save property" onClick={e=>{e.stopPropagation();save(p.id)}}><Heart size={18} fill={saved.includes(p.id)?'currentColor':'none'}/></button><span className="image-type"><BedDouble size={13}/> {p.configuration}</span></div><div className="property-body"><div className="price">{money(p.price)}<small className="per-month">{t('/mo','/મહિનો')}</small><span>{p.configuration}{p.area!=null&&<> · {p.area} {p.unit}</>}</span></div><button className="property-title" onClick={()=>D(p)}>{p.title}</button><p className="location"><MapPin size={14}/>{p.locality ? p.locality+' · ':''}{p.address}, Kosamba</p><div className="rent-deposit"><Wallet size={15}/><span>{t('Deposit','ડિપોઝિટ')}: {money(p.deposit)}</span></div><div className="property-bottom"><span className="owner-label"><UserRound size={14}/>{p.name}</span><button aria-label={t('View property','મિલકત જુઓ')} onClick={()=>D(p)}><ArrowRight size={19}/></button></div>
{tab==='mine'&&<div className="manage-actions"><button onClick={()=>MO(p)}><Pencil size={16}/>{t('Edit','ફેરફાર')}</button>{p.status==='approved'&&<button onClick={()=>action(()=>api(`/listings/${p.id}/sold`,{method:'PATCH'}))}><CheckCircle size={16}/>{t('Mark rented','ભાડે અપાયું')}</button>}<button onClick={()=>{if(confirm('Remove this listing?'))action(()=>api(`/listings/${p.id}`,{method:'DELETE'}))}}><Trash2 size={16}/>{t('Remove','દૂર કરો')}</button></div>}{tab==='admin'&&<div className="manage-actions">{['approved','rejected'].map(status=><button key={status} onClick={()=>action(()=>api(`/admin/listings/${p.id}`,{method:'POST',body:JSON.stringify({status})}))}>{status==='approved'?'Approve':'Reject'}</button>)}</div>}</div></article>)}</div>{!visible.length&&<div className="empty"><House size={32}/><h3>{t(ready?'No properties here yet':'Loading…',ready?'હજુ કોઈ મિલકત નથી':'લોડ થઈ રહ્યું છે…')}</h3><p>{t('List your property, or try another search.','મિલકત ઉમેરો અથવા બીજું સ્થળ શોધો.')}</p></div>}
{tab==='admin'&&<section><h2>Reported content</h2>{reports.map(r=><div className="setup-note" key={r.id}><strong>{r.reason}</strong><p>Listing: {r.listing||'—'} · Conversation: {r.conversation||'—'}</p>{r.listing&&<button className="primary" onClick={()=>action(()=>api(`/admin/listings/${r.listing}`,{method:'POST',body:JSON.stringify({status:'removed'})}))}>Remove reported listing</button>}</div>)}</section>}<div className="sell-banner"><House size={35}/><div><h2>{t('Your property. Someone’s new beginning.','તમારી મિલકત. કોઈની નવી શરૂઆત.')}</h2><p>{t('List for free. Connect privately, right here.','મફતમાં મિલકત ઉમેરો. અહીં ખાનગી વાત કરો.')}</p></div><button className="primary" onClick={()=>{if(needLogin())MO({})}}>{t('Start selling','વેચાણ શરૂ કરો')}<ArrowRight size={17}/></button></div><div className="trust-row"><div><ShieldCheck/><h3>{t('Reviewed before listing','પ્રકાશન પહેલાં સમીક્ષા')}</h3><p>{t('Every new listing and edit goes through review. Always check ownership documents yourself.','દરેક નવી મિલકત અને ફેરફારની સમીક્ષા થાય છે. માલિકીના દસ્તાવેજો જાતે તપાસો.')}</p></div><div><MessageCircle/><h3>{t('Talk here. Stay private.','અહીં વાત કરો. ખાનગી રહો.')}</h3><p>{t('Phone numbers remain private. Report or block unwanted conversations.','ફોન નંબર ખાનગી રહે છે. અનિચ્છનીય વાતચીત બ્લોક કે રિપોર્ટ કરો.')}</p></div><div><MapPin/><h3>{t('Made for Gujarat','ગુજરાત માટે')}</h3><p>{t('Homes, plots, farms and land. No payments through this app.','ઘર, પ્લોટ, ખેતર અને જમીન. એપમાં કોઈ ચૂકવણી નથી.')}</p></div></div></main></>:<Chat user={user} conversations={convs} active={chat} onSelect={next=>{if(next)CH(next);else goBack()}} onRead={id=>C(prev=>prev.map(c=>c.id===id?{...c,unread:0}:c))}/>}

<footer><a className="brand" href="/" onClick={e=>{e.preventDefault();CH(null);MO(null);D(null);T('explore')}}>KosRent.</a><span>{t('A place to find your place.','તમારી જગ્યા શોધવાનું સ્થળ.')}</span><span>© {new Date().getFullYear()} · Gujarat</span></footer>
{detail&&<div className="overlay"><section className="modal detail" role="dialog" aria-modal="true" aria-label="Property"><button className="close" onClick={goBack} aria-label="Close"><X/></button><PhotoSlider property={detail} detail/><div className="modal-content"><h2>{detail.title}</h2><p className="location"><MapPin size={17}/>{detail.locality ? detail.locality+' · ':''}{detail.address}, Kosamba</p><div className="rent-deposit"><Wallet size={17}/>{t('Deposit','ડિપોઝિટ')}: {money(detail.deposit)}<UserRound size={17}/>{detail.name}</div><div className="detail-stats"><strong>{money(detail.price)} <small>{t('/month','/મહિનો')}</small></strong><span>{detail.configuration}{detail.area!=null&&<> · {detail.area} {detail.unit}</>}</span></div><p>{detail.furnishing}</p>{detail.description&&<p>{detail.description}</p>}{detail.map&&<div className="map-reference"><MapPin size={16}/><span>Google location (reference only)</span><p>{detail.map}</p></div>}<p className="demo-note">{t('Check legal ownership, permissions and boundaries before any transaction. No payments are handled by KosRent.','વ્યવહાર પહેલાં માલિકી, પરવાનગીઓ અને સીમાઓ તપાસો. KosRent કોઈ ચૂકવણી લેતું નથી.')}</p>{detail.owner!==user?.id&&detail.status==='approved'&&<button className="primary full" onClick={()=>startChat(detail)}><MessageCircle size={18}/>{t('Chat with owner','માલિક સાથે વાત કરો')}</button>}<button className="report" onClick={()=>report(detail)}><Flag size={16}/>{t('Report listing','લિસ્ટિંગ રિપોર્ટ કરો')}</button></div></section></div>}
{modal==='profile'&&<div className="overlay"><section className="modal profile-sheet" role="dialog" aria-modal="true" aria-label={t('Profile','પ્રોફાઇલ')}><button className="close" aria-label="Close" onClick={goBack}><X/></button><div className="modal-content"><div className="profile-avatar"><UserRound size={36}/></div><h2>{user?user.name:t('Welcome to KosRent','KosRent માં સ્વાગત')}</h2><p>{user?user.email:t('Sign in to list rentals and chat.','વેચવા અને વાત કરવા સાઇન ઇન કરો.')}</p><PolicyLinks/><div className="profile-actions">{user?<><button onClick={()=>{MO(null);T('mine')}}><Building2/>{t('My listings','મારી મિલકતો')}<ArrowRight/></button><button onClick={()=>action(async()=>{await api('/logout',{method:'POST'});U(null);T('explore');CH(null);M([]);C([]);MO(null)})}><LogOut/>{t('Sign out','સાઇન આઉટ')}</button></>:<a href="/auth/google"><LogIn/>{t('Continue with Google','Google સાથે આગળ વધો')}<ArrowRight/></a>}</div></div></section></div>}
{modal&&modal!=='profile'&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="Listing form"><button className="close" onClick={goBack} aria-label="Close"><X/></button><div className="modal-content"><ListingForm t={t} initial={modal} onDone={()=>{MO(null);T('mine');refresh();N(t('Your home is published. View it on Home.','ડેટાબેઝમાં સાચવ્યું. સમીક્ષા બાકી છે.'))}}/></div></section></div>}
</>}
function ListingForm({t,initial,onDone}) {
 const [busy,B]=useState(false),[err,E]=useState(''),[kind,K]=useState('House'),[district]=useState('Surat');
 const units=['sq ft'];
 const field=(name,en,gj,type='text',required=true)=><label key={name}>{t(en,gj)}<input name={name} defaultValue={name==='name'?formatOwnerName(initial[name]||''):initial[name]||''} onBlur={name==='name'?e=>{e.target.value=formatOwnerName(e.target.value)}:undefined} type={type} required={required} min={type==='number'?'0.01':undefined} step={type==='number'?'any':undefined} pattern={name==='phone'?'[6-9][0-9]{9}':undefined}/></label>;
 return <><h2>{t(initial.id?'Edit rental':'Rent out your home',initial.id?'ભાડાની વિગતો સુધારો':'તમારું ઘર ભાડે આપો')}</h2><p>{t('Complete the details below. Your home will be published immediately.','નીચેની વિગતો ભરો. પ્રકાશન પહેલાં લિસ્ટિંગની સમીક્ષા થશે.')}</p><form className="listing-form" onSubmit={async e=>{e.preventDefault();B(true);E('');try{const f=new FormData(e.target),d=Object.fromEntries(f);d.price=Number(d.price);d.area=d.area===''?null:Number(d.area);d.deposit=Number(d.deposit);d.purpose='rent';d.type='House';d.district='Surat';d.village='Kosamba';const files=f.getAll('photos').filter(x=>x.size);if(files.length>5)throw Error('Choose no more than 5 photos.');if(files.some(x=>x.size>3*1024*1024))throw Error('Each photo must be under 3 MB.');if(files.length){const up=new FormData();files.forEach(x=>up.append('photos',x));d.photos=(await api('/photos',{method:'POST',body:up})).photos}else d.photos=initial.photos||[];delete d.authority;d.accepted=true;d.policyVersion='2026-10-07-free';await api(initial.id?`/listings/${initial.id}`:'/listings',{method:initial.id?'PUT':'POST',body:JSON.stringify(d)});onDone()}catch(e){E(e.message)}finally{B(false)}}}>
 {field('name','Owner’s name','માલિકનું નામ')}
 <input name="type" type="hidden" value="House"/><input name="purpose" type="hidden" value="rent"/>
 <input name="district" type="hidden" value="Surat"/><input name="village" type="hidden" value="Kosamba"/><p className="location"><MapPin size={16}/>Kosamba, Surat</p>
 <label>Area / locality<select name="locality" required defaultValue={initial.locality||''}><option value="">Select locality</option>{rentalAreas.map(area=><option key={area}>{area}</option>)}</select></label>
 {field('address','Exact address / location','ચોક્કસ સરનામું / સ્થળ')}
 <label>Photos (optional, up to 5, max 3 MB each)<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple/>{initial.id&&<small>Leave empty to keep existing photos. Selecting new photos replaces the current set.</small>}</label>
 <label>Furnishing<select name="furnishing" required defaultValue={initial.furnishing||''}><option value="">Select furnishing</option>{['Semi furnished','Fully furnished','Unfurnished'].map(value=><option key={value}>{value}</option>)}</select></label>
 {kind==='House'&&<label>{t('House configuration','ઘરનો પ્રકાર')}<select name="configuration" required defaultValue={initial.configuration||''}><option value="">{t('Select rooms','રૂમ પસંદ કરો')}</option>{['1 BHK','2 BHK','3 BHK'].map(x=><option key={x}>{x}</option>)}</select></label>}
 {field('area','Area (sq ft, optional)',kind==='House'?'વિસ્તાર (ચો. ફૂટ)':'વિસ્તાર','number',false)}
 <label>{t('Area unit','વિસ્તારનો એકમ')}<select name="unit" key={kind} defaultValue={units.includes(initial.unit)?initial.unit:units[0]}>{units.map(x=><option key={x} value={x}>{t(x,{'sq ft':'ચો. ફૂટ',acres:'એકર',vigha:'વીઘા'}[x])}</option>)}</select>{kind!=='House'&&kind!=='Plot'&&<small>{t('Vigha varies by locality; no automatic acre conversion.','વીઘાનું માપ વિસ્તાર પ્રમાણે બદલાય છે; એકરમાં આપમેળે રૂપાંતર થતું નથી.')}</small>}</label>
 {field('price','Monthly rent (₹)','માસિક ભાડું (₹)','number')}
 <label>{t('Refundable deposit (₹)','પરત મળતી ડિપોઝિટ (₹)')}<input name="deposit" type="number" min="0" step="1" defaultValue={initial.deposit??''} required/></label>
 {field('phone','Private phone number','ખાનગી ફોન નંબર','tel')}<small>Your number is stored privately and is not shown to renters.</small>
 {field('map','Google Maps link (optional)','Google Maps લિંક (વૈકલ્પિક)','url',false)}<small>Shown to renters as non-clickable reference text.</small>
 <label>{t('Description (optional)','વર્ણન')}<textarea name="description" maxLength={1500} defaultValue={initial.description||''}/></label>
 <p className="period-note">Listing your home is free. No renewal payment or automatic expiry applies during the free launch.</p><PolicyLinks/><label className="checkbox"><input type="checkbox" required/>I am 18 or older and accept the Terms, Privacy Notice and Refund Policy.</label>
 <label className="checkbox"><input name="authority" type="checkbox" required/>{t('I confirm these details are accurate and I am authorised to list this property.','વિગતો સાચી છે અને મને આ મિલકત ઉમેરવાનો અધિકાર છે.')}</label>
 {err&&<p className="error" role="alert">{err}</p>}<button className="primary full" disabled={busy}>{busy?t('Saving…','સાચવી રહ્યા છીએ…'):t('Publish home','સમીક્ષા માટે મોકલો')}</button>
 </form></>;
}
